kafka-producer:
  delayMs: 500
  topic: string-values
  properties:
    "[client.id]": kafka-producer
    "[bootstrap.servers]": localhost:9092
    "[acks]": 'all'
    "[key.serializer]": org.apache.kafka.common.serialization.LongSerializer
    "[value.serializer]": org.apache.kafka.common.serialization.StringSerializer
    "[batch.size]": 16384
    "[linger.ms]": 0
    "[enable.idempotence]": true
    "[retries]": 3